src/SAC/Models/Cliente.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.CompilerServices;

namespace SAC.Models
{
    public class Cliente
    {
        [Key]
        [DisplayName("CPF/CNPJ")]
        [Required]
        public string Documento { get; set; }

        [RegularExpression("([0-9]+)")]
        public string Matricula { get; set; }
        [MaxLength(100)]
        [Required]
        public string Nome { get; set; }
        
        [EmailAddress]
        public string Email { get; set; }
        
        [Phone]
        [Required]
        public string Fone { get; set; }

        public bool IsCPF => Documento.Length <= 12;
    }
    
}

src/SAC/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SAC.Data;
using SAC.Models;

namespace SAC.Controllers
{
    public class ClienteController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly int MAX = 1000;
        public ClienteController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Cliente
        public async Task<IActionResult> Index()
        {
            return View(await _context.Cliente.Take(MAX).ToListAsync());
        }
        [HttpGet]
        public async Task<IActionResult> BuscaGeral(string busca)
        {
            var result =_context.Cliente.Where(p => 
            p.Documento == busca || p.Matricula == busca || p.Nome.Contains(busca))
                .Take(MAX);
            ViewBag.Busca = busca;
            return View("Index", await result.ToListAsync());
        }


        // GET: Cliente/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _context.Cliente
                .FirstOrDefaultAsync(m => m.Documento == id);
            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }

        // GET: Cliente/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Cliente/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Documento,Matricula,Nome,Email,Fone")] Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cliente);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(cliente);
        }

        // GET: Cliente/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _context.Cliente.FindAsync(id);
            if (cliente == null)
            {
                return NotFound();
            }
            return View(cliente);
        }

        // POST: Cliente/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Documento,Matricula,Nome,Email,Fone")] Cliente cliente)
        {
            if (id != cliente.Documento)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cliente);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClienteExists(cliente.Documento))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cliente);
        }

        private bool ClienteExists(string id)
        {
            return _context.Cliente.Any(e => e.Documento == id);
        }
    }
}

src/SAC/Controllers/ProtocoloController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Query;
using SAC.Controllers.Common;
using SAC.Controllers.Requests;
using SAC.Data;
using SAC.Models;

namespace SAC.Controllers
{
    public class ProtocoloController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProtocoloController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Protocolo
        public async Task<IActionResult> Index([FromQuery] PesquisaProtocolo request)
        {
            var query = _context.Protocolos
                .Include(p => p.Assunto)
                .Include(p => p.Cliente)
                .Include(p => p.Motivo)
                .Include(p => p.Setor).AsQueryable();

            query = Filtra(query, request);
            ViewBag.Filtro = request;
            return View(await query.ToListAsync());
        }

        private IQueryable<Protocolo> Filtra(IQueryable<Protocolo> query, PesquisaProtocolo request)
        {
            if (request != null)
            {
                if (!String.IsNullOrEmpty(request.ProtocoloId))
                    query = query.Where(p => p.ProtocoloId == request.ProtocoloId);
                if (!String.IsNullOrEmpty(request.DigitroId))
                    query = query.Where(p => p.DigitroId == request.DigitroId);
                if (!String.IsNullOrEmpty(request.Nome))
                    query = query.Where(p => p.Cliente.Nome.Contains(request.Nome));
                if (!String.IsNullOrEmpty(request.Documento))
                    query = query.Where(p => p.ClienteId == request.Documento);
            }
            return query;
        }



        // GET: Protocolo/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var protocolo = await _context.Protocolos
                .Include(p => p.Assunto)
                .Include(p => p.Cliente)
                .Include(p => p.Motivo)
                .Include(p => p.Setor)
                .FirstOrDefaultAsync(m => m.ProtocoloId == id);
            if (protocolo == null)
            {
                return NotFound();
            }

            return View(protocolo);
        }

        
        public async Task<IActionResult> Create(string id)
        {
            var model = new Protocolo(true);
            model.Cliente = _context.Cliente.Single(c => c.Documento == id);
            model.ClienteId = id;
            LoadSelectList(model.Cliente);
            return View(model);
        }

      
        private void LoadSelectList(Cliente cliente)
        {
            ViewData["AssuntoId"] = new SelectList(_context.Assunto, nameof(Assunto.Id), nameof(Assunto.Nome));
            ViewData["ClienteId"] = new SelectList(new List<Cliente>() { cliente}, nameof(Cliente.Documento), nameof(Assunto.Nome));
            ViewData["MotivoId"] = new SelectList(_context.Motivo,
                nameof(Motivo.Id),
                nameof(Motivo.Nome));
            ViewData["SetorId"] = new SelectList(_context.Setor, nameof(Setor.Id), nameof(Setor.Nome));
        }

        // POST: Protocolo/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProtocoloId,DigitroId,ClienteId,SetorId,Observacao,MotivoId,AssuntoId,DtCriacao,DtAlterado")] Protocolo protocolo)
        {
            ValidaChavesUnitarias(protocolo);
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Add(protocolo);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception exc)
                {
                    ViewBag.Error = exc.Message;
                }
            }
            LoadSelectList(protocolo.Cliente);
            return View(protocolo);
        }

        private void ValidaChavesUnitarias(Protocolo protocolo)
        {
            if (ProtocoloExists(protocolo.ProtocoloId))
            {
                ModelState.AddModelError(nameof(protocolo.ProtocoloId), "Protocolo já existe");
            }
            if (DigitroIdExists(protocolo.DigitroId))
            {
                ModelState.AddModelError(nameof(protocolo.DigitroId), "Digitro já existe");
            }
        }

        // GET: Protocolo/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var protocolo = await _context.Protocolos.Include(c => c.Cliente).SingleAsync(d => d.ProtocoloId ==  id);
            if (protocolo == null)
            {
                return NotFound();
            }

            LoadSelectList(protocolo.Cliente);
            return View(protocolo);
        }

        // POST: Protocolo/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("ProtocoloId,DigitroId,ClienteId,SetorId,Observacao,MotivoId,AssuntoId,DtCriacao,DtAlterado")] Protocolo protocolo)
        {
            if (id != protocolo.ProtocoloId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(protocolo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProtocoloExists(protocolo.ProtocoloId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            LoadSelectList(await _context.Cliente.FindAsync(protocolo.ClienteId));
            return View(protocolo);
        }
       
        private bool ProtocoloExists(string id)
        {
            return _context.Protocolos.Any(e => e.ProtocoloId == id);
        }
        private bool DigitroIdExists(string digitroId)
        {
            return _context.Protocolos.Any(e => e.DigitroId == digitroId);
        }
    }
}

src/SAC/Views/Cliente/Create.cshtml
@model SAC.Models.Cliente

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Cliente</h4>
<hr />
<div class="row">
    <div class="col-md-8">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Documento" class="control-label"></label>
                <input asp-for="Documento" class="form-control" />
                <span asp-validation-for="Documento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Matricula" class="control-label"></label>
                <input asp-for="Matricula" class="form-control" />
                <span asp-validation-for="Matricula" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fone" class="control-label"></label>
                <input asp-for="Fone" class="form-control" />
                <span asp-validation-for="Fone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/SAC/Views/Cliente/Delete.cshtml
@model SAC.Models.Cliente

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Cliente</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Matricula)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Matricula)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fone)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Documento" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

src/SAC/Views/Cliente/Details.cshtml
@model SAC.Models.Cliente

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Cliente</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Matricula)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Matricula)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fone)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Documento">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

src/SAC/Views/Cliente/Edit.cshtml
@model SAC.Models.Cliente

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Cliente</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Documento" />
            <div class="form-group">
                <label asp-for="Matricula" class="control-label"></label>
                <input asp-for="Matricula" class="form-control" />
                <span asp-validation-for="Matricula" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fone" class="control-label"></label>
                <input asp-for="Fone" class="form-control" />
                <span asp-validation-for="Fone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/SAC/Views/Cliente/Index.cshtml
@model IEnumerable<SAC.Models.Cliente>

@{
    ViewData["Title"] = "Index";
}

<h1>Cliente</h1>
<div>
    @{
        if (@ViewBag.Busca != null)
        {
            @ViewBag.Busca
            <a asp-action="Index">x</a>
            
        }
    }
    </div>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Documento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Matricula)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fone)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Documento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Matricula)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fone)
            </td>
            <td>
                <a asp-controller="Protocolo" asp-action="Create" asp-route-id="@item.Documento">
                    +
                </a>
                <a asp-action="Edit" asp-route-id="@item.Documento">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Documento">Details</a> |
                
            </td>
        </tr>
}
    </tbody>
</table>